### PR TITLE
Update sabre/dav to 3.0.9 for windows 10 support

### PR DESCRIPTION
**Pull request by nickvergessen**

### CODE REVIEW

**Comment by nickvergessen** [comment]
@DeepDiver1975 @LukasReschke @rullzer

**Comment by rullzer** [comment]
According to https://github.com/fruux/sabre-dav/releases/tag/3.0.9 the 3.0.9 release ships with vobject 3.5.1. I prefer (on master) to upgrade whole releases.

**Comment by nickvergessen** [comment]
composer.json of sabre-dav 3.0.9 requires ^3.3.4, which does not match 3.5.x

**Comment by rullzer** [comment]
mmmm, ok... fine by me then :) :+1:

**Pull request merged**
