### PR TITLE
Fix owncloud/calendar#853 by applying parts of fruux/sabre-dav@ca91f5a

### PR DESCRIPTION
**Pull request by jakobsack**
This patch fixes owncloud/calendar#853 by backporting a patch from the sabredav repository.

The upstream patch is for Sabre 3.1

### CODE REVIEW

**Comment by nickvergessen** [comment]
https://github.com/fruux/sabre-dav/commit/ca91f5a nice find.

**Comment by MorrisJobke** [comment]
cc @PVince81 @DeepDiver1975

**Comment by nickvergessen** [comment]
I'd say this is okay to backport, if someone with WP confirms it

**Comment by jakobsack** [comment]
At least 3 people (including myself) confirmed it works under WP (see owncloud/calendar#853). 

However, @DeepDiver1975 does not like the idea of patching downstream. Neither do I, but from my POV it's more important to fix the issue for ownCloud stable8.1now and use a clean upstream solution for master (see #182)

**Comment by DeepDiver1975** [comment]
Please get in touch with @evert to see if the fix can be applied to 2.1.x as well

**Comment by jakobsack** [comment]
PR created: fruux/sabre-dav#692

Let's see if @evert accepts this PR and when the next 2.1 version is released ...

**Comment by jakobsack** [comment]
This patch has been applied upstream, sabredav 2.1.6 will likely be ready for ownCloud 8.1.1

**Comment by nickvergessen** [comment]
https://github.com/fruux/sabre-dav/tree/2.1.6

Preparing update

**Pull request closed without merging**
