### PR TITLE
Update sabre-dav to 2.1.6

### PR DESCRIPTION
**Pull request by nickvergessen**
@DeepDiver1975 @jakobsack @MorrisJobke 

Replaces #186

### CODE REVIEW

**Comment by nickvergessen** [comment]
Upstream diff for comparison:
https://github.com/fruux/sabre-dav/compare/2.1.3...2.1.6

**Comment by DeepDiver1975** [comment]
thx @nickvergessen - we need to update master as well

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@nickvergessen core pr already available? THX

**Pull request merged**
