### PR TITLE
Icewind streams 0.3.0

### PR DESCRIPTION
**Pull request by rullzer**
### DO NOT MERGE.. core pr is failing

Next packge randomly selected for bump

### CODE REVIEW

**Comment by rullzer** [comment]
Mmmm the new autoloader did some magic that I did not intent... let me fix that tomorrow by properly rebasing...

core pr will be created then.

**Comment by rullzer** [comment]
Core PR in https://github.com/owncloud/core/issues/20034

**Comment by DeepDiver1975** [comment]
rebase required

**Comment by rullzer** [comment]
@DeepDiver1975 I'll fix that once we fix the failing stuff in core :)

**Pull request merged**
