### PR TITLE
Update doctrine/dbal to 2.5.1

### PR DESCRIPTION
**Pull request by VicDeo**
Closes owncloud/core#13303

### CODE REVIEW

**Comment by PVince81** [comment]
Who can review this ? @DeepDiver1975 @icewind1991 @bantu @LukasReschke

**Comment by DeepDiver1975** [comment]
Just testing this on oracle ...

**Comment by DeepDiver1975** [comment]
unit tests run fine on oracle :heavy_check_mark:

**Comment by DeepDiver1975** [comment]
ready to merge from my understanding

**Pull request merged**
