### PR TITLE
Add guzzle

### PR DESCRIPTION
**Pull request by LukasReschke**
- [ ] Remove tests

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
30k SLOC? WOW

**Comment by LukasReschke** [comment]
Yup. But it also includes the tests and doc now yet.

Fun fact: we ship it already three times now… No idea how to clean up this mess :see_no_evil: 

1. https://github.com/owncloud/3rdparty/tree/master/guzzle
2. https://github.com/owncloud/core/tree/master/apps/files_external/3rdparty/aws-sdk-php/Guzzle
3. Now here 

:see_no_evil:

**Comment by DeepDiver1975** [comment]
> https://github.com/owncloud/3rdparty/tree/master/guzzle

Why not re-use this one instead of pulling it in again?

**Comment by LukasReschke** [comment]
> Why not re-use this one instead of pulling it in again?

I only did a `composer.phar require guzzlehttp/guzzle` as per http://guzzle.readthedocs.org/en/latest/overview.html#installation and would expect composer to be clever enough…?

@nickvergessen Any idea?

**Comment by DeepDiver1975** [comment]
hmm ... does that opencloud thingy require a different guzzle? https://github.com/owncloud/3rdparty/pull/99/files#diff-cf63dd6b61d2b5f3c0ac2793071d418aR25

**Comment by LukasReschke** [comment]
https://packagist.org/packages/guzzle/guzzle

> PHP HTTP client. This library is deprecated in favor of https://packagist.org/packages/guzzlehttp/guzzle

They use Guzzle 3 while we use Guzzle 5 :see_no_evil:

**Comment by nickvergessen** [comment]
Well `guzzlehttp/guzzle` is a different thind then `guzzle/guzzle` and `guzzle/http`

I'd add it to composer.json manually (which we really should sort alphabetically one day), and then run `composer.phar install *packagename*`

**Comment by LukasReschke** [comment]
Could that create namespace problems…? Maybe we should use 3 as well until the other awesome libraries we use have updated? :see_no_evil:

**Comment by LukasReschke** [comment]
As discussed with @nickvergessen I'll switch to 3.8 as well, but we have to update once 3.8 goes EoL as per https://github.com/guzzle/guzzle3/commit/d898326a716f23fdd778942ea9404aeccbe16a46

(which either means forcing Rackspace to update or replace that Rackspace library)

**Comment by LukasReschke** [comment]
Closing this one then.

**Comment by LukasReschke** [comment]
Okay. Still valid approach – uses a different namespace starting with Guzzle 4 so it's backwards compatible. What a mess :see_no_evil:

**Pull request closed without merging**
