### PR TITLE
update JSqueeze to version 2.0.4

### PR DESCRIPTION
**Pull request by georgehrke**
backport of https://github.com/owncloud/3rdparty/pull/266

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Backport of 3rdparty libs are currently on hold due to issues in the updater ....

**Comment by georgehrke** [comment]
ok 😞

**Comment by MorrisJobke** [comment]
Ping?

**Comment by mmattel** [comment]
Should´nt we skip that and backport https://github.com/owncloud/3rdparty/pull/275 (yet another jsqueeze update (2.0.5) ) when this one is merged?

**Comment by MorrisJobke** [comment]
> Should´nt we skip that and backport #275 (yet another jsqueeze update (2.0.5) ) when this one is merged?

Ah right -> close

**Pull request closed without merging**
