### PR TITLE
[stable9] Update to sabre 3.0.8 for fseek regression fix

### PR DESCRIPTION
**Pull request by PVince81**
Not a direct backport of https://github.com/owncloud/3rdparty/pull/258 due to composer file conflicts.
So I ran this:
```
± % composer update sabre/dav
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing sabre/dav (3.0.7)
  - Installing sabre/dav (3.0.8)
    Loading from cache

Writing lock file
Generating optimized autoload files
```

It does NOT update sabre/xml and other deps.

Please review @DeepDiver1975 @icewind1991 

- [x] backport approval pending https://github.com/owncloud/3rdparty/pull/258#issue-140939717 @karlitschek

### CODE REVIEW

**Comment by PVince81** [comment]
core PR for submodule+CI https://github.com/owncloud/core/pull/23307

**Comment by icewind1991** [comment]
:+1:

**Comment by karlitschek** [comment]
hmm.  seems that we have to do this. Backport is fine after some good testing

**Comment by PVince81** [comment]
I have retested this with https://github.com/owncloud/core/issues/22476#issuecomment-196764305 and it works fine

**Comment by PVince81** [comment]
Let me test a few more external storages with and without encryption

**Comment by PVince81** [comment]
In all cases, I tested downloading bacon.txt with and without range requests.

#### Without encryption
- [x] TEST: Dropbox
- [x] TEST: GDrive
- [x] TEST: ownCloud
- [x] TEST: S3
- [x] TEST: SFTP
- [x] TEST: SMB
- [x] TEST: download from shared storage as recipient

#### With encryption
- [x] TEST: Dropbox
- [x] TEST: GDrive
- [x] TEST: ownCloud
- [x] TEST: S3
- [x] TEST: SFTP
- [x] TEST: SMB
- [x] TEST: download from shared storage as recipient

**Comment by rullzer** [comment]
:+1:

**Comment by PVince81** [comment]
will update submodule in https://github.com/owncloud/core/pull/23307

**Pull request merged**
