### PR TITLE
[9.0] update icewind/streams to 0.4.0

### PR DESCRIPTION
**Pull request by icewind1991**

### CODE REVIEW

**Comment by PVince81** [comment]
Tested SMB, still works :+1: 

I'm not too happy about those changes in the CallbackWrapper though, which could affect other parts of the code

**Comment by PVince81** [comment]
Can you rebase due to conflicts ?
(and also adjust the core PR)

Thanks

**Comment by schiesbn** [comment]
:+1:

**Comment by icewind1991** [comment]
rebased

**Comment by PVince81** [comment]
Still works :+1:

**Pull request merged**
