### PR TITLE
Sabre patch for recursive PROPFIND and "0" folders

### PR DESCRIPTION
**Pull request by PVince81**
@LukasReschke @MorrisJobke @DeepDiver1975 @nickvergessen 

- [x] Wait for https://github.com/fruux/sabre-dav/pull/677 to be merged upstream

### CODE REVIEW

**Comment by PVince81** [comment]
Fixes PROPFIND issue discovered here https://github.com/owncloud/client/issues/3351#issuecomment-112732908

**Comment by PVince81** [comment]
(but does not fix the upload issue in that ticket)

**Comment by nickvergessen** [comment]
odd, should add a smashbox test for folders and files named 0 I guess?

**Comment by PVince81** [comment]
@nickvergessen see https://github.com/owncloud/smashbox/issues/114
not sure if it's worth writing a completely separate lonely test for that.

**Comment by PVince81** [comment]
Upstream patch https://github.com/fruux/sabre-dav/pull/677 was merged.

We'll still need to patch the local library until we upgrade to next Sabre version, probably 3.0.2 once it's out...

**Comment by DeepDiver1975** [comment]
We can also wait for 2.1.5 being released - https://github.com/fruux/sabre-dav/commit/d64aa406a13775f9d2411f512bc041f9e49682a3

**Comment by PVince81** [comment]
Ah nice, I didn't see any backport notice. Maybe they don't do it like we do :smile:

**Comment by DeepDiver1975** [comment]
> Maybe they don't do it like we do :smile:

No :wink: - Evert just merged the changes to all release branches

**Comment by jakobsack** [comment]
Patch integrated in  Sabre 2.1.6, merged in #187 and #188

**Pull request closed without merging**
