### PR TITLE
Update Archive_Tar to 1.4.0 for PHP 7 compatibility

### PR DESCRIPTION
**Pull request by LukasReschke**
Following test script still worked:
```php
<?php

require_once './lib/base.php';

$foo = OC_Archive::open('./test.tar.gz');
var_dump($foo->getFiles());
```

@DeepDiver1975

### CODE REVIEW

**Comment by LukasReschke** [comment]
Will create a PR in core after https://github.com/owncloud/core/pull/18024 has been merged due to rebasing.

**Comment by MorrisJobke** [comment]
Tested and archives still look fine :+1:

**Comment by DeepDiver1975** [comment]
> Will create a PR in core after owncloud/core#18024 has been merged due to rebasing.

or we simply update the submodule in there

**Comment by LukasReschke** [comment]
Done https://github.com/owncloud/core/pull/18024#issuecomment-127599516

**Pull request merged**
