### PR TITLE
Support empty password in basic auth

### PR DESCRIPTION
**Pull request by LukasReschke**
This is a backport of https://github.com/fruux/sabre-dav/issues/596 to the version used by ownCloud. Without this S2S is not working in some server environments.

This patch has been confirmed to work by @jnfrmarks.

Fixes https://github.com/owncloud/core/issues/13398 and https://github.com/owncloud/core/issues/13486

@DeepDiver1975 @karlitschek Without this S2S is broken in some envs. For me this is clearly a 8.0 target.

### CODE REVIEW

**Comment by jnfrmarks** [comment]
I validated this changing the file locally on both owncloud systems I am using for testing.

**Comment by LukasReschke** [comment]
Upstream commit: https://github.com/fruux/sabre-dav/commit/49104623ae10caf58649a93f25de6b098de60f0f

**Comment by LukasReschke** [comment]
@AdamWill FYI – packaging fun.

**Comment by LukasReschke** [comment]
Please notice that due to the ungraceful handling of failures by S2S this means that if the remote host does not have this patch applied all files are inaccessible for the user…

We really need to make the S2S functionality handling failures more gracefully. @jnfrmarks agreed to test the behaviour when S2S remote servers are going down (etc…) so I'm pretty confident we can expect some tickets about this soon.

**Comment by AdamWill** [comment]
@LukasReschke thanks for the heads-up!

**Comment by jnfrmarks** [comment]
No pressure!

**Comment by DeepDiver1975** [comment]
fine with me :+1:

**Comment by DeepDiver1975** [comment]
@LukasReschke do we have any information from @evert on a release date of 1.8.12 ?

**Comment by LukasReschke** [comment]
Changelog says "not known": https://github.com/fruux/sabre-dav/blob/29d85943e0098eae11607001e67ec9b4cc2633c1/ChangeLog ;-)

I'm pretty confident though that @evert may know more about that topic ;-)

**Comment by icewind1991** [comment]
Code looks good :+1:

**Comment by evert** [comment]
When would you guys like it by? I can accommodate.

**Comment by DeepDiver1975** [comment]
> When would you guys like it by? I can accommodate.

We will bundle OC8 RC by the end of this week latest - would be great to get it in by then? :speak_no_evil:

**Comment by evert** [comment]
Can do... will try to get this done tomorrow.

**Comment by DeepDiver1975** [comment]
> Can do... will try to get this done tomorrow.

youre-awesome

**Comment by evert** [comment]
Just released it:

https://github.com/fruux/sabre-dav/releases/tag/1.8.12

Not doing a formal announcement, because it's a rather small change that affects no one I think :)

**Comment by DeepDiver1975** [comment]
THX a lot @evert

**Comment by LukasReschke** [comment]
No one except us crazy folks ;-)

Thank you @evert. I'll update this PR to use the composer version.

**Comment by DeepDiver1975** [comment]
@LukasReschke let's pull 1.8.12 via composer instead of this manual changes

**Comment by evert** [comment]
You guys use composer now?

**Comment by LukasReschke** [comment]
"It depends". For core we still have our own autoloader (which we plan to replace with 8.1 or so) and for dependencies we use composer. But we use it "our way" which is updating the dependency and then uploading the generated files to this repository.

**Comment by LukasReschke** [comment]
PR is updated.

**Comment by LukasReschke** [comment]
Changeset is that big because I dumped an optimized autoloader: https://getcomposer.org/doc/03-cli.md#dump-autoload

**Comment by AdamWill** [comment]
@LukasReschke FWIW that's kind of a pain for downstream distribution. It effectively hardcodes the file location for *every single class you pull in via composer*. The way composer works, if a path is specified for a class in `autoload_classmap.php`, that is the *only* place Composer will look for it; it'll just flat `require()` that location and everything will explode if it's not there.

What the 'optimized autoloader' thing does is simply generate an entry in `autoload_classmap.php` for every single class provided by something pulled in via composer. So once you've done that, it breaks distribution fallback to loading from the system include path.

We really hate that mechanism - to unbundle anything that uses classmap autoloading we just have to symlink the system-wide copy into the expected location, which is kinda horrible.

We have the option of patching out the classmap mechanism from the composer autoloader entirely, but then we have to make sure we unbundle *everything* that uses classmap such that it can be found systemwide. If we can't do that we have to patch the autoloader to check the location found via classmap and fall through the other mechanisms if it doesn't exist, which is yet more downstream-specific patching...:/

**Comment by LukasReschke** [comment]
Well – that file was already there before and just not used for all classes: https://github.com/owncloud/3rdparty/blob/85260798f95159e293ad3831131d06cdc37be55c/composer/autoload_classmap.php

I guess that's what you have to fight with anyways when doing some custom packaging magic ;-)

**Comment by AdamWill** [comment]
@LukasReschke yes, but this makes it much, much worse. The classes that were already listed there before are from composer packages that specify 'classmap' as their autoload mechanism in their `composer.json` - usually because they use some kind of completely non-logical layout and it's the only practical option. We do have to deal with those ones, yes, as I wrote in the initial post - we have to symlink the system wide copies into the expected locations. But usually there's only a few files to deal with; if every single class is in there, it would just be ridiculously unwieldy to go around symlinking every single unbundled file into place; if you keep this, I'll have to switch to one of the 'patch the autoloader' strategies.

**Comment by LukasReschke** [comment]
Pff, then let me be nice to you and use the regular autoloader…

Did I already mention that I'm not a fan of distro packages? ;-) *hides*

**Comment by LukasReschke** [comment]
@AdamWill Happier now? ;-)

**Comment by AdamWill** [comment]
yay! thanks ;)

If you really want to go this way, it's not a blocker, it's just yet one more on the big pile of PHP Packaging Annoyances - but I'd really appreciate if you maybe did a bit of profiling and checked that it actually improves performance appreciably, at least, rather than just throwing it in on general principles :)

**Pull request merged**
