### PR TITLE
Delete spurious ZIP file

### PR DESCRIPTION
**Pull request by DavidPrevot**
This binary file was added by mistake on https://github.com/owncloud/3rdparty/pull/97.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

cc @LukasReschke @DeepDiver1975

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@MorrisJobke please open pr in core to update the submodule - thx

**Comment by MorrisJobke** [comment]
owncloud/core#15302

**Pull request merged**
