### PR TITLE
Bump sabre/dav to 2.1.9

### PR DESCRIPTION
**Pull request by rullzer**
For https://github.com/owncloud/core/issues/21914

### CODE REVIEW

**Comment by RealRancor** [comment]
Cc @DocLambda @redhell @despens @cwmenke from https://github.com/owncloud/calendar/issues/1002

@skjnldsv @Noctivivans from https://github.com/owncloud/core/issues/21461

**Comment by skjnldsv** [comment]
I went back to php 5, sorry, can't test! :/

**Comment by cwmke** [comment]
Everything seems to be working well on Android and IOS.  Thanks!

**Comment by Bodenseematze** [comment]
I also tested it in my OC 8.2.2 installation  - seems to work well. Big thanks!

Only thing I see in the logging:
`Array to string conversion at /home/www/owncloud8.2.2/lib/private/template/functions.php#36`
and
`Installation is in transit between the old Encryption (ownCloud <= 8.0) and the new encryption. Please enable the "Default encryption module" and run 'occ encryption:migrate'`
(which I assume is because I don't have encryption enabled - and I don't want it to enable, made too much trouble in the past)

**Pull request merged**
