### PR TITLE
Use optimized autoloader

### PR DESCRIPTION
**Pull request by LukasReschke**
Saves a few ms per request (actually pretty much considering relative numbers, we measured 5-15ms - this is huge for WebDAV requests!). This has not been done in the past as it caused problems for unofficial packages. _IF_ distributions decide to do Frankenstein releases where they remove some libraries or move it to a system-wide one then they would have to modify this file as well.

I consider this absolutely sensible given that this overall is an improvement. If somebody wants to do such unsupported releases they should be able to also adjust this as well

@rullzer As discussed.
@DeepDiver1975 FYI - please make sure that all PRs are always using `--optimize-autoloader`.

### CODE REVIEW

**Comment by LukasReschke** [comment]
Core: https://github.com/owncloud/core/pull/20024

**Comment by rullzer** [comment]
:+1: yes please!!

**Comment by LukasReschke** [comment]
Aha! It is possible to set such values in composer.json. Let's try this.

**Comment by Xenopathic** [comment]
:+1:

Now we just need core using Composer directly too, then everything will be super fast!

**Comment by karlitschek** [comment]
Agreed. :+1:

**Pull request merged**
