### PR TITLE
Update to Sabre 2.1

### PR DESCRIPTION
**Pull request by PVince81**
Update to Sabre 2.1, for https://github.com/owncloud/core/issues/12876

Unless we want 2.0 instead ?
Should I remove the "tests" subfolders ?

@DeepDiver1975 @icewind1991

### CODE REVIEW

**Comment by PVince81** [comment]
Conflict... will re-push

**Comment by PVince81** [comment]
Here we go, up to date.

**Comment by LukasReschke** [comment]
> Should I remove the "tests" subfolders ?

Yes please. – All tests and examples should go away for now.

**Comment by DeepDiver1975** [comment]
> Should I remove the "tests" subfolders ?

yes please - thx

**Comment by PVince81** [comment]
Done

**Comment by PVince81** [comment]
I was told that there is 2.1.2. I naively typed in "2.1.0" before.

Will redo this branch with an update to 2.1.2

**Comment by PVince81** [comment]
Done, this is now 2.1.2 :-)

**Comment by osos** [comment]
Sorry to inform, that version 2.1.3 has been released: http://sabre.io/blog/2015/sabre-dav-2.1.3-released/

with "upgrade highly recommended"

**Pull request merged**
