### PR TITLE
Sabre update to 3.0.0

### PR DESCRIPTION
**Pull request by PVince81**
@rullzer @LukasReschke @DeepDiver1975 

Note: please don't merge until we are sure that it doesn't break core.
I'll have a test there.

### CODE REVIEW

**Comment by PVince81** [comment]
Pyocclient tests fail with Sabre 3
Looks like this will need some adaptation in core.

**Comment by PVince81** [comment]
cadaver still works, but pyocclient doesn't.

It looks like Sabre doesn't recognize the session cookies any more ?

**Comment by jakobsack** [comment]
Hi, there is a very important patch for CalDAV + Windows Phone in Sabre 3.1. Would it be possible to upgrade to 3.1.0?

Further Information:

* fruux/sabre-dav@ca91f5a9603e53cd4edef2749996ae600cf742a9
* fruux/sabre-dav#685
* owncloud/calendar#853

**Comment by nickvergessen** [comment]
The comment from @jakobsack will be addressed by updating to 2.1.6 in the meantime #188

**Comment by PVince81** [comment]
@DeepDiver1975 should we move forward with this ? Upgrading to 3.1 instead of 3.0 ?

**Comment by phsc** [comment]
SabreDAV 3.1 requires PHP 5.5, whereas SabreDAV 3.0 only requires PHP 5.4.

**Comment by PVince81** [comment]
Hmmm, good point. Sabre 3.0 would already fix a few known issues, so it would be a nice step forward.

**Comment by DeepDiver1975** [comment]
> Hmmm, good point. Sabre 3.0 would already fix a few known issues, so it would be a nice step forward.

let me see ... taking over

**Comment by DeepDiver1975** [comment]
superseeded by https://github.com/owncloud/core/pull/20636

**Pull request closed without merging**
