### PR TITLE
3rdparty components are living in core since oc10

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by PVince81** [comment]
I suggest adding a README to state that "3rdparty components are living in core since oc10" instead of having it completely empty

**Comment by DeepDiver1975** [comment]
> I suggest adding a README to state that "3rdparty components are living in core since oc10" instead of having it completely empty

done

**Comment by PVince81** [comment]
please also backport this to the stable10 branch

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/3rdparty/tree/stable10

**Pull request merged**
