### PR TITLE
Update phpseclib to 2.0 for increased PHP7 compatibility

### PR DESCRIPTION
**Pull request by bantu**
New Features Include:

* Minimum PHP Version 5.3.3
* PSR-4 autoloading with namespace rooted at `\phpseclib\`
 * Removal of PHP4 constructors
 * Removal of manual includes
 * One class per file
* Refactoring of function files into classes
* Some refactoring of defined constants into class constants (only true constants)
* Removal of side-effects from class files
* Removal of full license text from source code files
* Removal of the `phpseclib_resolve_include_path` function

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
THX @bantu

**Comment by srt10coupe** [comment]
update my 3rdparty -> ownCloud site does not open.

**Comment by DeepDiver1975** [comment]
will be fixed with this PR in core - https://github.com/owncloud/core/pull/18024

**Pull request merged**
