### PR TITLE
Bump php-opencloud to 1.15.0 including deps

### PR DESCRIPTION
**Pull request by rullzer**
Huge update. Lets see what the master CI thinks of this.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
WOW 8,5k SLOC :exclamation: 

@karlitschek this hugh pile of code is only required if swift external is used - just another reason for me to carefully review our external storage code base, split this into a separate app and even consider publishing this via the appstore. Only those who really want swift secondary storage should pull this code base into their installation.

@icewind1991 flysystem has no swift adapter - right?

**Comment by DeepDiver1975** [comment]
> @karlitschek this hugh pile of code is only required if swift external is used - just another reason for me to carefully review our external storage code base, split this into a separate app and even consider publishing this via the appstore. Only those who really want swift secondary storage should pull this code base into their installation.

Grrrr :imp: this is also used for the primary objectstore integration! What a mess!!!!

**Comment by icewind1991** [comment]
> @icewind1991 flysystem has no swift adapter - right?

There is a "rackspace" adapter but I dont know if that also does generic swift

**Comment by karlitschek** [comment]
@DeepDiver1975 Uff. Yes. This could be in the 3rdparty folder of the swift app. Of course if it's also used be the primary storage integration then we have to have it in the core 3rdparty unfortunately. Life is no apple pie ;-)

**Comment by DeepDiver1975** [comment]
> Yes. This could be in the 3rdparty folder of the swift app. Of course if it's also used be the primary storage integration then we have to have it in the core 3rdparty unfortunately. Life is no apple pie ;-)

we still have the option to move the primary swift storage to an app as well - the alternative s3 and rados primary objectstores are in apps as well

**Comment by rullzer** [comment]
Lets close this for now since fixing it in core will take to much time.

**Pull request closed without merging**
