### PR TITLE
yet another jsqueeze update (2.0.5)

### PR DESCRIPTION
**Pull request by georgehrke**
update jsqueeze to version 2.0.5

fixes https://github.com/owncloud/calendar/issues/451

@DeepDiver1975 @MorrisJobke

### CODE REVIEW

**Comment by mmattel** [comment]
Any reason why we do not merge?

**Comment by PVince81** [comment]
Did anyone test this ? If yes, please state what you tested so we might not need to do it again :smile:

**Comment by georgehrke** [comment]
stable9: https://github.com/owncloud/3rdparty/pull/276

**Comment by mmattel** [comment]
Any progress?
Would fix the unpleasant calendar bug!

**Comment by PVince81** [comment]
@mmattel if you tested this on master and can confirm that JS still works, then we can count this as a thumbs up

**Comment by PVince81** [comment]
need to comment out these for testing https://github.com/owncloud/calendar/blob/master/controller/viewcontroller.php#L67

Somehow can't reproduce the original issue on master. The calendar colors look fine without this PR.

**Comment by PVince81** [comment]
(and I have asset pipeline enabled)

**Comment by PVince81** [comment]
I noticed that if I refresh the page, the calendar color is not saved. This happens with both this PR and without.

@georgehrke please provide steps to reproduce and test.
We're close to feature freeze and if we do get this in we need to make sure it actually fixes the issue and also doesn't break other apps.

**Comment by georgehrke** [comment]
The original issue with not being able to use the calendar was fixed in an earlier PR (https://github.com/owncloud/3rdparty/pull/266), but that one was not back ported to stable9.
2.0.5 fixes yet another issue which causes all calendars to have the same color.

**Comment by PVince81** [comment]
Then it looks like it doesn't work. Regardless what color I set for a calendar, when I refresh the page it always displays orange.

**Comment by PVince81** [comment]
Please provide the detailed testing steps. The original ticket doesn't contain any.

**Comment by georgehrke** [comment]
Ok, so:
- disable asset pipeline
- create a few calendars with different colors
- enable asset pipeline (and comment out check in viewController)
- reload page
- all calendars are orange
- __delete /assets__
- reload page
- calendar will appear with different colors again

**Comment by PVince81** [comment]
@georgehrke thanks a lot.

Tested, works :+1: 

@mmattel @rullzer @nickvergessen second review ?

**Comment by MorrisJobke** [comment]
:+1:

**Comment by PVince81** [comment]
@georgehrke please open a PR in core to adjust the submodule

**Comment by georgehrke** [comment]
yes, will do

**Pull request merged**
