### PR TITLE
Add a variable normalizer for logs

### PR DESCRIPTION
**Pull request by oparoz**
Adds https://github.com/interfasys/lognormalizer for https://github.com/owncloud/core/pull/12682

### CODE REVIEW

**Comment by LukasReschke** [comment]
You seem to have forgotten to check-in the source files? :speak_no_evil:

**Comment by oparoz** [comment]
Thanks! For some reason, the top folder was not highlighted as new in PHPStorm and I missed it...

**Comment by oparoz** [comment]
Apparently, it's harder than it should to commit composer libs fetched from git...

**Comment by MorrisJobke** [comment]
I rebased this on master.

**Comment by oparoz** [comment]
Thanks!

**Pull request merged**
