### PR TITLE
Remove unneeded files

### PR DESCRIPTION
**Pull request by MorrisJobke**
* tests, binaries, changelogs

cc @nickvergessen @DeepDiver1975 @LukasReschke

### CODE REVIEW

**Comment by nickvergessen** [comment]
fine by me, but we have other conflicting and waiting PRs

**Comment by DeepDiver1975** [comment]
please add them to gitignore

**Comment by MorrisJobke** [comment]
> please add them to gitignore

They are already. It seems that they are force added or were checked in before the gitignore statement was added.

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by nickvergessen** [comment]
:+1:

**Pull request merged**
